//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnomeExtractor.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loc() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GnomeExtractor.Resources.Loc", typeof(Loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AnimalHusbandry ähnelt.
        /// </summary>
        internal static string AnimalHusbandry {
            get {
                return ResourceManager.GetString("AnimalHusbandry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Armor ähnelt.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ArmorCrafting ähnelt.
        /// </summary>
        internal static string ArmorCrafting {
            get {
                return ResourceManager.GetString("ArmorCrafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Axe ähnelt.
        /// </summary>
        internal static string Axe {
            get {
                return ResourceManager.GetString("Axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die backup saved to: ähnelt.
        /// </summary>
        internal static string backupDoneMessage {
            get {
                return ResourceManager.GetString("backupDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blacksmithing ähnelt.
        /// </summary>
        internal static string Blacksmithing {
            get {
                return ResourceManager.GetString("Blacksmithing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brawling ähnelt.
        /// </summary>
        internal static string Brawling {
            get {
                return ResourceManager.GetString("Brawling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brewing ähnelt.
        /// </summary>
        internal static string Brewing {
            get {
                return ResourceManager.GetString("Brewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Butchery ähnelt.
        /// </summary>
        internal static string Butchery {
            get {
                return ResourceManager.GetString("Butchery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caretaking ähnelt.
        /// </summary>
        internal static string Caretaking {
            get {
                return ResourceManager.GetString("Caretaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carpentry ähnelt.
        /// </summary>
        internal static string Carpentry {
            get {
                return ResourceManager.GetString("Carpentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charm ähnelt.
        /// </summary>
        internal static string Charm {
            get {
                return ResourceManager.GetString("Charm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File selected: ähnelt.
        /// </summary>
        internal static string chosenFile {
            get {
                return ResourceManager.GetString("chosenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection error ähnelt.
        /// </summary>
        internal static string connectionError {
            get {
                return ResourceManager.GetString("connectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Construction ähnelt.
        /// </summary>
        internal static string Construction {
            get {
                return ResourceManager.GetString("Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cooking ähnelt.
        /// </summary>
        internal static string Cooking {
            get {
                return ResourceManager.GetString("Cooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crossbow ähnelt.
        /// </summary>
        internal static string Crossbow {
            get {
                return ResourceManager.GetString("Crossbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Curiosity ähnelt.
        /// </summary>
        internal static string Curiosity {
            get {
                return ResourceManager.GetString("Curiosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dodge ähnelt.
        /// </summary>
        internal static string Dodge {
            get {
                return ResourceManager.GetString("Dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die go to the official website to download? ähnelt.
        /// </summary>
        internal static string downloadNewVersion {
            get {
                return ResourceManager.GetString("downloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Engineering ähnelt.
        /// </summary>
        internal static string Engineering {
            get {
                return ResourceManager.GetString("Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only integers from  1 to 50000 are accepted ähnelt.
        /// </summary>
        internal static string errorFastEditValue {
            get {
                return ResourceManager.GetString("errorFastEditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Gnome&apos;s name may not exceed 24 characters ähnelt.
        /// </summary>
        internal static string errorGridEditName {
            get {
                return ResourceManager.GetString("errorGridEditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export tables to CSV completed successfully. Please, check Export folder ähnelt.
        /// </summary>
        internal static string exportDoneMessage {
            get {
                return ResourceManager.GetString("exportDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farming ähnelt.
        /// </summary>
        internal static string Farming {
            get {
                return ResourceManager.GetString("Farming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fighting ähnelt.
        /// </summary>
        internal static string Fighting {
            get {
                return ResourceManager.GetString("Fighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fitness ähnelt.
        /// </summary>
        internal static string Fitness {
            get {
                return ResourceManager.GetString("Fitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus ähnelt.
        /// </summary>
        internal static string Focus {
            get {
                return ResourceManager.GetString("Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Gnomoria.exe not found, please install the program in game folder ähnelt.
        /// </summary>
        internal static string gameNotFound {
            get {
                return ResourceManager.GetString("gameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gem Cutting ähnelt.
        /// </summary>
        internal static string GemCutting {
            get {
                return ResourceManager.GetString("GemCutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gun ähnelt.
        /// </summary>
        internal static string Gun {
            get {
                return ResourceManager.GetString("Gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammer ähnelt.
        /// </summary>
        internal static string Hammer {
            get {
                return ResourceManager.GetString("Hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hauling ähnelt.
        /// </summary>
        internal static string Hauling {
            get {
                return ResourceManager.GetString("Hauling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horticulture ähnelt.
        /// </summary>
        internal static string Horticulture {
            get {
                return ResourceManager.GetString("Horticulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jewelry Making ähnelt.
        /// </summary>
        internal static string JewelryMaking {
            get {
                return ResourceManager.GetString("JewelryMaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No updates avaiable at this time, you have lastest version ähnelt.
        /// </summary>
        internal static string latestVersion {
            get {
                return ResourceManager.GetString("latestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leatherworking ähnelt.
        /// </summary>
        internal static string Leatherworking {
            get {
                return ResourceManager.GetString("Leatherworking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Localization file not found for that language ähnelt.
        /// </summary>
        internal static string localizationNotFound {
            get {
                return ResourceManager.GetString("localizationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File loclib.dll not found, please reinstall the program ähnelt.
        /// </summary>
        internal static string loclibNotFound {
            get {
                return ResourceManager.GetString("loclibNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Machining ähnelt.
        /// </summary>
        internal static string Machining {
            get {
                return ResourceManager.GetString("Machining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This action cannot be undone. Use on your own risk! ähnelt.
        /// </summary>
        internal static string make65535 {
            get {
                return ResourceManager.GetString("make65535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Masonry ähnelt.
        /// </summary>
        internal static string Masonry {
            get {
                return ResourceManager.GetString("Masonry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mechanic ähnelt.
        /// </summary>
        internal static string Mechanic {
            get {
                return ResourceManager.GetString("Mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medic ähnelt.
        /// </summary>
        internal static string Medic {
            get {
                return ResourceManager.GetString("Medic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metalworking ähnelt.
        /// </summary>
        internal static string Metalworking {
            get {
                return ResourceManager.GetString("Metalworking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mining ähnelt.
        /// </summary>
        internal static string Mining {
            get {
                return ResourceManager.GetString("Mining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found a more recent version: ähnelt.
        /// </summary>
        internal static string newestVersion {
            get {
                return ResourceManager.GetString("newestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nimbleness ähnelt.
        /// </summary>
        internal static string Nimbleness {
            get {
                return ResourceManager.GetString("Nimbleness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pottery ähnelt.
        /// </summary>
        internal static string Pottery {
            get {
                return ResourceManager.GetString("Pottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Профессия ähnelt.
        /// </summary>
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profession with same title already exists ähnelt.
        /// </summary>
        internal static string professionAlreadyExists {
            get {
                return ResourceManager.GetString("professionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All changes are saved to the source file: ähnelt.
        /// </summary>
        internal static string saveDoneMessage {
            get {
                return ResourceManager.GetString("saveDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shield ähnelt.
        /// </summary>
        internal static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smelting ähnelt.
        /// </summary>
        internal static string Smelting {
            get {
                return ResourceManager.GetString("Smelting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stonecarving ähnelt.
        /// </summary>
        internal static string Stonecarving {
            get {
                return ResourceManager.GetString("Stonecarving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sword ähnelt.
        /// </summary>
        internal static string Sword {
            get {
                return ResourceManager.GetString("Sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tailoring ähnelt.
        /// </summary>
        internal static string Tailoring {
            get {
                return ResourceManager.GetString("Tailoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tinkering ähnelt.
        /// </summary>
        internal static string Tinkering {
            get {
                return ResourceManager.GetString("Tinkering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are trying to open a file from a wrong directory. ähnelt.
        /// </summary>
        internal static string tryWrongPath {
            get {
                return ResourceManager.GetString("tryWrongPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        internal static string updateDialogCaption {
            get {
                return ResourceManager.GetString("updateDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string warn {
            get {
                return ResourceManager.GetString("warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weapon Crafting ähnelt.
        /// </summary>
        internal static string WeaponCrafting {
            get {
                return ResourceManager.GetString("WeaponCrafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weaving ähnelt.
        /// </summary>
        internal static string Weaving {
            get {
                return ResourceManager.GetString("Weaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Woodcarving ähnelt.
        /// </summary>
        internal static string Woodcarving {
            get {
                return ResourceManager.GetString("Woodcarving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Woodcutting ähnelt.
        /// </summary>
        internal static string Woodcutting {
            get {
                return ResourceManager.GetString("Woodcutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die World name: ähnelt.
        /// </summary>
        internal static string worldName {
            get {
                return ResourceManager.GetString("worldName", resourceCulture);
            }
        }
    }
}
