//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnomeExtractor.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loc() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GnomeExtractor.Resources.Loc", typeof(Loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AnimalHusbandry.
        /// </summary>
        internal static string AnimalHusbandry {
            get {
                return ResourceManager.GetString("AnimalHusbandry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Armor.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ArmorCrafting.
        /// </summary>
        internal static string ArmorCrafting {
            get {
                return ResourceManager.GetString("ArmorCrafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Axe.
        /// </summary>
        internal static string Axe {
            get {
                return ResourceManager.GetString("Axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на backup saved to:.
        /// </summary>
        internal static string backupDoneMessage {
            get {
                return ResourceManager.GetString("backupDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blacksmithing.
        /// </summary>
        internal static string Blacksmithing {
            get {
                return ResourceManager.GetString("Blacksmithing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brawling.
        /// </summary>
        internal static string Brawling {
            get {
                return ResourceManager.GetString("Brawling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brewing.
        /// </summary>
        internal static string Brewing {
            get {
                return ResourceManager.GetString("Brewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Butchery.
        /// </summary>
        internal static string Butchery {
            get {
                return ResourceManager.GetString("Butchery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Caretaking.
        /// </summary>
        internal static string Caretaking {
            get {
                return ResourceManager.GetString("Caretaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carpentry.
        /// </summary>
        internal static string Carpentry {
            get {
                return ResourceManager.GetString("Carpentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Charm.
        /// </summary>
        internal static string Charm {
            get {
                return ResourceManager.GetString("Charm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File selected:.
        /// </summary>
        internal static string chosenFile {
            get {
                return ResourceManager.GetString("chosenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection error.
        /// </summary>
        internal static string connectionError {
            get {
                return ResourceManager.GetString("connectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Construction.
        /// </summary>
        internal static string Construction {
            get {
                return ResourceManager.GetString("Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cooking.
        /// </summary>
        internal static string Cooking {
            get {
                return ResourceManager.GetString("Cooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Crossbow.
        /// </summary>
        internal static string Crossbow {
            get {
                return ResourceManager.GetString("Crossbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Curiosity.
        /// </summary>
        internal static string Curiosity {
            get {
                return ResourceManager.GetString("Curiosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dodge.
        /// </summary>
        internal static string Dodge {
            get {
                return ResourceManager.GetString("Dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go to the official website to download?.
        /// </summary>
        internal static string downloadNewVersion {
            get {
                return ResourceManager.GetString("downloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Engineering.
        /// </summary>
        internal static string Engineering {
            get {
                return ResourceManager.GetString("Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only integers from  1 to 50000 are accepted.
        /// </summary>
        internal static string errorFastEditValue {
            get {
                return ResourceManager.GetString("errorFastEditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Gnome&apos;s name may not exceed 24 characters.
        /// </summary>
        internal static string errorGridEditName {
            get {
                return ResourceManager.GetString("errorGridEditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export tables to CSV completed successfully. Please, check Export folder.
        /// </summary>
        internal static string exportDoneMessage {
            get {
                return ResourceManager.GetString("exportDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Farming.
        /// </summary>
        internal static string Farming {
            get {
                return ResourceManager.GetString("Farming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fighting.
        /// </summary>
        internal static string Fighting {
            get {
                return ResourceManager.GetString("Fighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fitness.
        /// </summary>
        internal static string Fitness {
            get {
                return ResourceManager.GetString("Fitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Focus.
        /// </summary>
        internal static string Focus {
            get {
                return ResourceManager.GetString("Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Gnomoria.exe not found, please install the program in game folder.
        /// </summary>
        internal static string gameNotFound {
            get {
                return ResourceManager.GetString("gameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gem Cutting.
        /// </summary>
        internal static string GemCutting {
            get {
                return ResourceManager.GetString("GemCutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gun.
        /// </summary>
        internal static string Gun {
            get {
                return ResourceManager.GetString("Gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hammer.
        /// </summary>
        internal static string Hammer {
            get {
                return ResourceManager.GetString("Hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hauling.
        /// </summary>
        internal static string Hauling {
            get {
                return ResourceManager.GetString("Hauling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Horticulture.
        /// </summary>
        internal static string Horticulture {
            get {
                return ResourceManager.GetString("Horticulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jewelry Making.
        /// </summary>
        internal static string JewelryMaking {
            get {
                return ResourceManager.GetString("JewelryMaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No updates avaiable at this time, you have lastest version.
        /// </summary>
        internal static string latestVersion {
            get {
                return ResourceManager.GetString("latestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leatherworking.
        /// </summary>
        internal static string Leatherworking {
            get {
                return ResourceManager.GetString("Leatherworking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Localization file not found for that language.
        /// </summary>
        internal static string localizationNotFound {
            get {
                return ResourceManager.GetString("localizationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File loclib.dll not found, please reinstall the program.
        /// </summary>
        internal static string loclibNotFound {
            get {
                return ResourceManager.GetString("loclibNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Machining.
        /// </summary>
        internal static string Machining {
            get {
                return ResourceManager.GetString("Machining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This action cannot be undone. Use on your own risk!.
        /// </summary>
        internal static string make65535 {
            get {
                return ResourceManager.GetString("make65535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Masonry.
        /// </summary>
        internal static string Masonry {
            get {
                return ResourceManager.GetString("Masonry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mechanic.
        /// </summary>
        internal static string Mechanic {
            get {
                return ResourceManager.GetString("Mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medic.
        /// </summary>
        internal static string Medic {
            get {
                return ResourceManager.GetString("Medic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metalworking.
        /// </summary>
        internal static string Metalworking {
            get {
                return ResourceManager.GetString("Metalworking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mining.
        /// </summary>
        internal static string Mining {
            get {
                return ResourceManager.GetString("Mining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found a more recent version:.
        /// </summary>
        internal static string newestVersion {
            get {
                return ResourceManager.GetString("newestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nimbleness.
        /// </summary>
        internal static string Nimbleness {
            get {
                return ResourceManager.GetString("Nimbleness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pottery.
        /// </summary>
        internal static string Pottery {
            get {
                return ResourceManager.GetString("Pottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профессия.
        /// </summary>
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profession with same title already exists.
        /// </summary>
        internal static string professionAlreadyExists {
            get {
                return ResourceManager.GetString("professionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All changes are saved to the source file:.
        /// </summary>
        internal static string saveDoneMessage {
            get {
                return ResourceManager.GetString("saveDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shield.
        /// </summary>
        internal static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smelting.
        /// </summary>
        internal static string Smelting {
            get {
                return ResourceManager.GetString("Smelting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stonecarving.
        /// </summary>
        internal static string Stonecarving {
            get {
                return ResourceManager.GetString("Stonecarving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sword.
        /// </summary>
        internal static string Sword {
            get {
                return ResourceManager.GetString("Sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tailoring.
        /// </summary>
        internal static string Tailoring {
            get {
                return ResourceManager.GetString("Tailoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tinkering.
        /// </summary>
        internal static string Tinkering {
            get {
                return ResourceManager.GetString("Tinkering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are trying to open a file from a wrong directory..
        /// </summary>
        internal static string tryWrongPath {
            get {
                return ResourceManager.GetString("tryWrongPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        internal static string updateDialogCaption {
            get {
                return ResourceManager.GetString("updateDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        internal static string warn {
            get {
                return ResourceManager.GetString("warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weapon Crafting.
        /// </summary>
        internal static string WeaponCrafting {
            get {
                return ResourceManager.GetString("WeaponCrafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weaving.
        /// </summary>
        internal static string Weaving {
            get {
                return ResourceManager.GetString("Weaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Woodcarving.
        /// </summary>
        internal static string Woodcarving {
            get {
                return ResourceManager.GetString("Woodcarving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Woodcutting.
        /// </summary>
        internal static string Woodcutting {
            get {
                return ResourceManager.GetString("Woodcutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на World name:.
        /// </summary>
        internal static string worldName {
            get {
                return ResourceManager.GetString("worldName", resourceCulture);
            }
        }
    }
}
